[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm run dev:vite"
  functions = "netlify/functions"
  publish = "dist"
  port = 8888
  targetPort = 5173