[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable edge functions if not needed
[edge_functions]
  # No edge functions defined - this prevents Netlify from trying to set up Deno